# Generated by Django 6.0.1 on 2026-05-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('text', 'Text Question'), ('image_question', 'Image Question'), ('image_option', 'Image Option')], default='text', max_length=20)),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('option1_image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('option2_image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('option3_image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('animal', 'Animal')], max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parents.child'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.child')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.child')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.question')),
            ],
        ),
    ]
