# Generated by Django 6.0.1 on 2026-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('animal', 'Animal'), ('vegetable', 'Vegetable')], max_length=50),
        ),
    ]
