# Generated by Django 6.0.4 on 2026-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_activitylog_student_created_at_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default='easy', max_length=20),
        ),
    ]
