# Generated by Django 6.0.1 on 2026-05-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_delete_activitylog_alter_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testassignment',
            name='student',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='TestAssignment',
        ),
    ]
