# Generated by Django 6.0.1 on 2026-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
